In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

import warnings
warnings.filterwarnings("ignore")

In [2]:
#pkg = mp.jupyter.open_package()
pkg = mp.jupyter.open_source_package()
pkg

`sandiegodata.org-passonsoped-1.1.1` Last Update: 2020-09-27T18:08:37

__






## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [sdcrime_2016](data/2016.csv)**. San Diego crime suspects and victims, 2016, unprocessed
* ** [sdcrime_2017](data/2017.csv)**. San Diego crime suspects and victims, 2017
* ** [sdcrime_2018](data/2018.csv)**. San Diego crime suspects and victims, 2018
* ** [sdcrime_2019](data/2019.csv)**. San Diego crime suspects and victims, 2019
* ** [sdcrime_2020](data/2020.csv)**. San Diego crime suspects and victims, 2020
* ** [ucrcodes](data/CodeUCRLookup.csv)**. UCR codes and detailed descriptions
* ** [sdcrime_16_20](notebooks/process.ipynb)**. San Diego crime suspects and victims, 2016 to 2020, with extra geographic information

## References
<ul><li> <strong>census_blocks</string>, <em>data/census_blocks.csv</em>. Census 2010 blocks, converted to ACS geoids, with centroid position</li><ul>

In [3]:
df = pkg.resource('sdcrime_2016').dataframe()
df.head().T

,0,1,2,3,4
pk,12144871,12127327,12278698,12278698,12364997
activityNumber,'01600014','16000042','16005661','16005661','16008822'
activityType,CRIME CASE,CRIME CASE,CRIME CASE,CRIME CASE,CRIME CASE
activityDate,2016-01-01 00:00:00,2016-01-01 00:00:00,2016-01-01 00:00:00,2016-01-01 00:00:00,2016-01-01 00:00:00
year,2016,2016,2016,2016,2016
agency,NATIONAL CITY,SAN DIEGO,SAN DIEGO,SAN DIEGO,SAN DIEGO
violationSection,10851,459,488,488,487(A)
violationType,VC,PC,PC,PC,PC
chargeDescription,TAKE VEHICLE W/O OWNER'S CONSENT/VEHICLE THEFT,BURGLARY/UNSPECIFIED,PETTY THEFT,PETTY THEFT,GRAND THEFT:MONEY/LABOR/PROPERTY OVER $950
chargeLevel,FELONY,FELONY,MISDEMEANOR,MISDEMEANOR,FELONY
codeUcr,7A0,5A6,6DG,6DG,6AE
CrimeCategory,Vehicle Theft,Non Res Burglary,Larceny < $400,Larceny < $400,Larceny >= $400
highestChargeFlag,1,1,1,1,1
PersonRole,VICTIM,NaN,SUSPECT,VICTIM/WITNESS,VICTIM/WITNESS
Race,OTHER,NaN,WHITE,HISPANIC,WHITE
Age,NaN,NaN,28,74,70
sex,FEMALE,NaN,MALE,MALE,MALE
role,INCIDENT,INCIDENT,INCIDENT,INCIDENT,INCIDENT
zipCode,91950,92109,92115,92115,92109
censusBlock,'02000','20000','20230','20230','20120'
censusTract,'022000','007907','002902','002902','007905'
City,NATIONAL CITY,SAN DIEGO,SAN DIEGO,SAN DIEGO,SAN DIEGO

In [5]:
from geoid.acs import Tract, Block, AcsGeoid

def mk_tract_geoid(v):

    if v is None or v is np.nan:
        return None
    else:
        return str(Tract(6, 73, int(v) ))

def mk_bg_geoid(r):

    if r.censusTract is None or r.censusTract is np.nan or r.censusBlock is None or r.censusBlock is np.nan:
        return None
    else:
        return str(Block(6, 73, int(r.censusTract), int(r.censusBlock) ))

for r in pkg.resources():
    if 'crime' in r.name:
        break
        
print(r.name)

sdcrime_2016

In [ ]:
df = pd.concat(frames)

In [ ]:
blks = pkg.reference('census_blocks').dataframe().rename(columns={'geoid':'block_geoid'})
blks.head()

In [ ]:
df = df.merge(blks, on='block_geoid')

In [6]:
18/8

2.25

In [10]:
df[df.agency == 'SAN DIEGO'].head().T

,180,181,1593,1594,2177
pk,14270022,14270022,13318299,13318299,12482482
activityNumber,'17009609','17009609','16041437','16041437','16004394'
activityType,CRIME CASE,CRIME CASE,CRIME CASE,CRIME CASE,CRIME CASE
activityDate,2016-11-01 00:00:00,2016-11-01 00:00:00,2016-10-08 06:45:00,2016-10-08 06:45:00,2016-01-31 00:00:00
year,2016,2016,2016,2016,2016
agency,SAN DIEGO,SAN DIEGO,SAN DIEGO,SAN DIEGO,SAN DIEGO
violationSection,261(A)(2),261(A)(2),273.5A,273.5A,69
violationType,PC,PC,PC,PC,PC
chargeDescription,RAPE: FORCE/FEAR/ETC.,RAPE: FORCE/FEAR/ETC.,INFLICT CORPORAL INJURY ON SPOUSE/COHABITANT,INFLICT CORPORAL INJURY ON SPOUSE/COHABITANT,OBSTRUCT/RESIST EXECUTIVE OFFICER
chargeLevel,FELONY,FELONY,FELONY,FELONY,FELONY
codeUcr,2B0,2B0,4E0,4E0,4E0
CrimeCategory,Rape,Rape,Simple Assault,Simple Assault,Simple Assault
highestChargeFlag,1,1,1,1,1
PersonRole,SUSPECT,VICTIM/WITNESS,SUSPECT,VICTIM,SUSPECT
Race,OTHER,WHITE,HISPANIC,HISPANIC,HISPANIC
Age,NaN,19,37,34,52
sex,MALE,FEMALE,MALE,FEMALE,MALE
role,INCIDENT,INCIDENT,INCIDENT,INCIDENT,INCIDENT
zipCode,91942,91942,91911,91911,91950
censusBlock,02000,02000,01040,01040,02005
censusTract,014805,014805,013310,013310,011902
City,LA MESA,LA MESA,CHULA VISTA,CHULA VISTA,NATIONAL CITY
tract_geoid,14000US06073014805,14000US06073014805,14000US06073013310,14000US06073013310,14000US06073011902
block_geoid,10100US060730148052000,10100US060730148052000,10100US060730133101040,10100US060730133101040,10100US060730119022005
intptlat,32.7767,32.7767,32.6203,32.6203,32.6856
intptlon,-117.036,-117.036,-117.023,-117.023,-117.08
geometry,POINT (-117.0361197847325 32.77669757486128),POINT (-117.0361197847325 32.77669757486128),POINT (-117.0228822308434 32.62033910734949),POINT (-117.0228822308434 32.62033910734949),POINT (-117.0800916526166 32.68555759849126)

In [13]:
df['activityDate'] = pd.to_datetime(df['activityDate'])
df['year'] = df.activityDate.dt.year

0        2016
1        2016
2        2016
3        2016
4        2016
         ...
78744    2016
78745    2016
78746    2016
78747    2016
78748    2016
Name: activityDate, Length: 78749, dtype: int64